---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: stephane2029
    group_name: devops
  vars_files:
    - variables.yml
    
  tasks:
    - name: Check the time
      command: dategggh
#      when: ansible_distribution == "stephane" or ansible_processor_nproc == 2
    - name: create user stephane
      user:
         name: "{{user_name}}"
         comment: Stephane Admin
    - name: create group
      group:
         name: "{{group_name}}"
         state: present
    - name: Install package
      package:
        name: "{{pkg_name}}"
        state: present  
          